server.servlet.context-path: /egzamator-api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/egzamator?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ${egzamator.db.password}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update